-- =============================================================================
-- UniSOC Sentinel — PostgreSQL Schema Initialisation
-- =============================================================================
-- This file is executed once when the postgres container first starts.
-- It is mounted at /docker-entrypoint-initdb.d/init.sql (read-only).
--
-- Extensions, tables, indexes, triggers, and the default admin user are
-- created here. All UUIDs use gen_random_uuid() (pgcrypto).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Table: users
-- Stores operator accounts. Roles: admin, analyst, viewer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    username      VARCHAR(64)  UNIQUE NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL DEFAULT 'analyst'
                               CHECK (role IN ('admin', 'analyst', 'viewer')),
    is_active     BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_login    TIMESTAMPTZ
);

COMMENT ON TABLE  users                IS 'Operator accounts for the SIEM platform';
COMMENT ON COLUMN users.password_hash  IS 'bcrypt hash of the user password';
COMMENT ON COLUMN users.role           IS 'Access level: admin | analyst | viewer';

-- ---------------------------------------------------------------------------
-- Table: sessions
-- JWT refresh token registry. Allows server-side revocation.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash VARCHAR(255) NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at         TIMESTAMPTZ  NOT NULL,
    revoked            BOOLEAN      NOT NULL DEFAULT false,
    ip_address         INET,
    user_agent         TEXT
);

COMMENT ON TABLE sessions IS 'JWT refresh token registry; supports explicit revocation';

-- ---------------------------------------------------------------------------
-- Table: api_keys
-- Long-lived programmatic access credentials.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS api_keys (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         VARCHAR(128) NOT NULL,
    key_hash     VARCHAR(255) NOT NULL UNIQUE,
    key_prefix   CHAR(8)      NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at   TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    is_active    BOOLEAN      NOT NULL DEFAULT true
);

COMMENT ON TABLE  api_keys            IS 'Long-lived API key credentials';
COMMENT ON COLUMN api_keys.key_hash   IS 'SHA-256 hash of the full API key';
COMMENT ON COLUMN api_keys.key_prefix IS 'First 8 chars of the key (for display in UI)';

-- ---------------------------------------------------------------------------
-- Table: alerts
-- Alert records written by the alerting engine.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alerts (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_id          VARCHAR(128) NOT NULL,
    rule_name        VARCHAR(255) NOT NULL,
    severity         VARCHAR(32)  NOT NULL
                                  CHECK (severity IN ('critical', 'high', 'medium', 'low', 'info')),
    title            TEXT         NOT NULL,
    description      TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    acknowledged     BOOLEAN      NOT NULL DEFAULT false,
    acknowledged_by  UUID         REFERENCES users(id),
    acknowledged_at  TIMESTAMPTZ,
    event_count      INTEGER      NOT NULL DEFAULT 1,
    metadata         JSONB        NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE  alerts             IS 'Alert records generated by the alerting engine';
COMMENT ON COLUMN alerts.rule_id     IS 'Stable machine-readable rule identifier';
COMMENT ON COLUMN alerts.event_count IS 'Number of matching events aggregated into this alert';
COMMENT ON COLUMN alerts.metadata    IS 'Arbitrary rule-specific context (source IPs, device IDs, etc.)';

-- ---------------------------------------------------------------------------
-- Table: audit_log
-- Immutable record of all user and system actions.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID         REFERENCES users(id) ON DELETE SET NULL,
    action        VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64),
    resource_id   VARCHAR(255),
    details       JSONB,
    ip_address    INET,
    user_agent    TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  audit_log             IS 'Immutable audit trail of all operator and API actions';
COMMENT ON COLUMN audit_log.action      IS 'Verb describing the action (e.g. user.login, alert.acknowledge)';
COMMENT ON COLUMN audit_log.resource_type IS 'Entity type acted upon (e.g. user, alert, api_key)';
COMMENT ON COLUMN audit_log.resource_id  IS 'UUID or identifier of the affected resource';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- sessions
CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_sessions_expires_at
    ON sessions (expires_at)
    WHERE NOT revoked;

-- api_keys
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id
    ON api_keys (user_id);

CREATE INDEX IF NOT EXISTS idx_api_keys_is_active
    ON api_keys (is_active)
    WHERE is_active;

-- alerts
CREATE INDEX IF NOT EXISTS idx_alerts_created_at
    ON alerts (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_severity
    ON alerts (severity);

CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged
    ON alerts (acknowledged);

CREATE INDEX IF NOT EXISTS idx_alerts_rule_id
    ON alerts (rule_id);

CREATE INDEX IF NOT EXISTS idx_alerts_metadata_gin
    ON alerts USING gin (metadata);

-- audit_log
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id
    ON audit_log (user_id);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
    ON audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_action
    ON audit_log (action);

-- ---------------------------------------------------------------------------
-- Trigger: keep users.updated_at current
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_updated_at ON users;
CREATE TRIGGER users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Default admin user
-- password: ChangeMe123!
-- hash generated with:  python3 -c "import bcrypt; print(bcrypt.hashpw(b'ChangeMe123!', bcrypt.gensalt(12)).decode())"
-- ---------------------------------------------------------------------------
INSERT INTO users (username, email, password_hash, role)
VALUES (
    'admin',
    'admin@localhost',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewFX.0W6aqhe6Awe',
    'admin'
)
ON CONFLICT (username) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Done
-- ---------------------------------------------------------------------------
-- Schema initialised successfully.
-- Default credentials:  admin / ChangeMe123!
-- IMPORTANT: Change the admin password immediately after first login.
